export const FEATURED = [
  {
    handle: "can't-catch-harry",
    name: "Can't Catch Harry",
    id: "51u7riaQPd",
    min_players: 2,
    max_players: 6,
    min_playtime: 15,
    max_playtime: 30,
    min_age: 6,
    description:
      "Can’t Catch Harry is a fast paced card game that comes with collectors cards from the popular youtube channel The Odd 1s Out. The deck is made of characters your friends and family will recognize. You’ll spend many game nights trying to catch Harry before he and his friends are pulled into the lull of the Lamp (bug zapper). The game gets more intense with each round as players try to collect certain combinations of cards to give them a edge in the game.Save your moth friends from giving in to the glowing draw of the lamp. Every time you’re unable to match 4 of a kind, your moth risks being zapped! ",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1578612898657",
    year_published: 2019,
    primary_publisher: "Breaking Games",
    primary_designer: "James Rallison",
    developers: [],
    artists: ["James Rallison"],
    official_url:
      "https://theodd1sout.com/products/cant-catch-harry-pre-order-guaranteed-delivery-march-2019",
  },
  {
    handle: "happy-salmon",
    name: "Happy Salmon",
    id: "nErpFnUWwP",
    min_players: 3,
    max_players: 6,
    min_playtime: 15,
    max_playtime: 30,
    min_age: 6,
    description:
      "Happy Salmon is a quick party game for 3-8 players. Each player gets a stack of cards. Every card has a simple action that requires a partner. Players frantically shout their actions looking for matching players. When they find a match, they both complete the action and discard their used cards. The first player to finish all of their cards wins!",
    image_url:
      "https://cdn.shopify.com/s/files/1/0345/9180/1483/products/HS-CORE_PDPContent_DTC_1400x1400FOB_700x.png?v=1678406240",
    year_published: 2016,
    primary_publisher: "North Star Games",
    primary_designer: "Ken Gruhl",
    developers: [],
    artists: ["Linda DeSantis"],
    official_url: "https://www.explodingkittens.com/products/happy-salmon",
  },
  {
    handle: "king-of-tokyo",
    name: "King of Tokyo",
    id: "d5SOmqGHGr",
    min_players: 2,
    max_players: 6,
    min_playtime: 30,
    max_playtime: 36,
    min_age: 8,
    description:
      "King of Tokyo is a game for 2 to 6 players where you play as Mutant monsters, rampaging robots, or even abominable aliens battling in a fun, chaotic atmosphere.  Roll dice and choose your strategy: will you attack your enemies? Heal your wounds? improve your monster? Stomp your path to victory.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257600208-61doPBeJTjL.jpg",
    year_published: 2011,
    primary_publisher: "IELLO",
    primary_designer: "Richard Garfield",
    developers: [],
    artists: [
      "Gabriel Butik",
      "Romain Gaschet",
      "Igor Polouchine",
      "Benjamin Raynal",
      "Jean-Baptiste Reynaud",
      "Jonathan Silvertre",
      "Régis Torres",
      "Anthony Wolff",
    ],
    official_url: "https://iello.fr/jeux/king-of-tokyo/",
  },
  {
    handle: "shifting-stones",
    name: "Shifting Stones",
    id: "jXgm4bsGpT",
    min_players: 1,
    max_players: 5,
    min_playtime: 20,
    max_playtime: 20,
    min_age: 8,
    description:
      "Leave no stone unturned! Nine mystical tiles lie before you in a grid of rocky ruins. Rearrange the tiles to match one or more of the patterns in your hand. The catch is that you must sacrifice a card every time you swap or flip a tile. Carve out the most points in Shifting Stones, and your victory will be set in stone!",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1608196862716",
    year_published: 2020,
    primary_publisher: "Gamewright",
    primary_designer: "J. Evan Raitt",
    developers: [],
    artists: ["Kwanchai Moriya"],
    official_url: "https://gamewright.com/product/shifting-stones",
  },
  {
    handle: "fairy-tale-inn",
    name: "Fairy Tale Inn",
    id: "30mPBolkyn",
    min_players: 2,
    max_players: 2,
    min_playtime: 15,
    max_playtime: 20,
    min_age: 8,
    description:
      "In Fairy Tale Inn, players are looking to fill up their Inn with Guests. They’ll pick from different fairy tale characters on the Guest List and slide them into the vertical Inn. Every character has a special ability, and certain rooms do as well, giving gold to the players in different ways. When three columns of the Inn are filled, the points are tallied and the player with the most gold is the winner.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1636993834761",
    year_published: 2020,
    primary_publisher: "CMON Limited",
    primary_designer: "Remo Conzadori",
    developers: [],
    artists: ["Davide Tosello"],
    official_url:
      "https://www.cmon.com/product/fairy-tale-inn/fairy-tale-inn?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "umbra-via",
    name: "Umbra Via",
    id: "sdQctVGpKr",
    min_players: 2,
    max_players: 4,
    min_playtime: 30,
    max_playtime: 45,
    min_age: 8,
    description:
      "Just beyond the towering vines lies an ancient pathway into the unknown. Push back the thorn-riddled stocks to discover a clandestine garden, blooming with mysterious vigor. Vivid colors mark the way to intricate tiles zigging and zagging through the green. Within the flowers lies the key to greater meaning. An explanation for all things unknown... In Umbra Via, players compete to control and complete the most cunning paths. Reach into your bag to select wooden flowers, then place them on your secret board in the order of the paths you want most. But when players reveal their choices, things get delightfully tricky.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1629322880241.jpg",
    year_published: 2021,
    primary_publisher: "Pandasaurus Games",
    primary_designer: "",
    developers: [],
    artists: ["Eddie Schillo", "Stevo Torres"],
    official_url:
      "https://pandasaurusgames.com/collections/shop/products/umbra-via?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "cascadia",
    name: "Cascadia",
    id: "DcqF6LNGCi",
    min_players: 1,
    max_players: 4,
    min_playtime: 30,
    max_playtime: 45,
    min_age: 14,
    description:
      "In Cascadia, players compete to create the most harmonious ecosystem by selecting and adding habitats and wildlife to their environment. The goal in placing habitat tiles is to create contiguous corridors by matching rivers, prairies, wetlands, forests, and mountains. Once habitats are placed, players populate them with the wildlife species that each habitat supports. Each species has their own spatial requirements and connections to one another and their ecosystem! Cascadia is a modular, dual-layer puzzle, with variable scoring conditions that is simple to learn, but challenging to master! Cascadia comes with a variety of spatial wildlife goals allowing you to mix and match new challenges each and every time you play! There are hundreds of unique puzzles to explore! Create stunningly beautiful terrain maps as you build your own personal environment, while competing with others for the habitats and wildlife you desire!",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1600224809797",
    year_published: 2021,
    primary_publisher: "Flatout Games",
    primary_designer: "Randy Flynn",
    developers: [
      "Randy Flynn",
      "Molly Johnson",
      "Robert Melvin",
      "Kevin Russ",
      "Shawn Stankewich",
    ],
    artists: ["Beth Sobel"],
    official_url:
      "https://www.kickstarter.com/projects/flatoutgames/cascadia?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "queendomino",
    name: "Queendomino",
    id: "5ygNA78TL1",
    min_players: 2,
    max_players: 4,
    min_playtime: 25,
    max_playtime: 45,
    min_age: 8,
    description:
      "You are a royal, seeking new lands to expand your ever-growing kingdom. Explore and conquer the different terrains, and develop the best and richest territories for your people. Scour lands full of wheat fields, forests, grasslands, swamps, mines, and towns, diversifying your kingdom's riches along the way. Tax the lands wisely to fund the construction of your towns, pick the buildings you erect carefully, and try to win the Queen's favor - all while making sure your plans aren't foiled by the Dragon's flame. Make sure to strategize and acquire carefully, as others are also competing for the same lands, a stake in the riches, and the heart of the Queen! Queendomino is a game completely independent from Kingdomino, while offering a choice of more complex challenges. Two to four players can play Queendomino independently, but also in connection with Kingdomino, allowing for games with 7x7 grids for four players, or for up to six players if you stick to 5x5 grids.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254192344-61rke-hCe5L.jpg",
    year_published: 2017,
    primary_publisher: "Blue Orange Games",
    primary_designer: "Bruno Cathala",
    developers: [],
    artists: ["Cyril Bouquet"],
    official_url:
      "http://www.blueorangegames.com/index.php/games/queendomino?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "mastermind-game--the-strategy-game-of-codemaker-vs-codebreaker",
    name: "Mastermind",
    id: "VI2NUUImPt",
    min_players: 2,
    max_players: 2,
    min_playtime: 20,
    max_playtime: 20,
    min_age: 8,
    description:
      "Test your code-cracking prowess with Mastermind, the challenging game of logic and deduction. Can you crack the code in 10 moves or less? Can you create a code than can't be cracked? With more than 2,000 possible codes it’s different every time. The Codemaker sets a secret code, then the Codebreaker tries to match the code using logic, deduction, and maybe even a little bit of luck. After each move, the Codemaker gives clues to the Codebreaker. Make the code even more devious by using multiple pegs of the same color or by leaving one or more peg holes empty. Includes game console with built-in storage tray and code peg shield, 108 code pegs in 6 colors, 30 key pegs in two colors, and complete instructions.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254849802-61RL0r3ZedL.jpg",
    year_published: 1971,
    primary_publisher: "Pressman Toy Corp.",
    primary_designer: "Mordecai Meirowitz",
    developers: [],
    artists: [],
    official_url:
      "https://www.pressmantoy.com/wp-content/uploads/2018/07/3018K10_v1_0218_Mastermind_IM.pdf",
  },
  {
    handle: "go",
    name: "Go",
    id: "JyMsRC64I4",
    min_players: 2,
    max_players: 2,
    min_playtime: 30,
    max_playtime: 180,
    min_age: 8,
    description:
      "Go originated in China more than 4000 years ago. But it was the Japanese who perfected it and made Go a great strategic skill game. For thousands of years everyone from the working classes to royalty played Go, making it the national pastime. The popularity of Go has now reached the West bringing with it an air of Oriental wisdom and mystery! The Object of Go is to gain control of territories and capture enemy stones.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559254869478-81J9QN4EJKL.gif",
    year_published: 2000,
    primary_publisher: "John N. Hansen Co.",
    primary_designer: "",
    developers: [],
    artists: ["Barbro Hennius", "Norman Sommer"],
    official_url:
      "http://www.online-go.com?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "zombie-fluxx",
    name: "Zombie Fluxx",
    id: "tmvXEOgJVz",
    min_players: 2,
    max_players: 6,
    min_playtime: 10,
    max_playtime: 40,
    min_age: 8,
    description:
      "Crank up the fun as you face a rampage of brain-eating, shuffling Zombies in the form of Creeper cards. Their rigo-mortis-like movements will keep you from winning until you outsmart them. Grab a Chinsaw or Shotgun from the deck and cause your own rampage to win...if you can. Zombie Fluxx has just the right mix of random and strategy and begins with one basic rule: Draw one card, choose one card and follow the directions written on the card to make your play. As cards are drawn and played from the deck, the rules of the game change from how many cards are drawn, played or even how many cards you can hold at the end of your turn.For 2 - 5 players, ages 8 and up.Play time: 5 - 30 minutes.Although Zombie Fluxx is a stand alone game, you can combine it with other versions by mixing whole decks together or just your favorite rule cards for even more Fluxx fun! The other Fluxx titles we carry are as follows: Monty Python Fluxx Eco Fluxx Martian Fluxx Family Fluxx",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257925865-510MUA2BFxJL.jpg",
    year_published: 2007,
    primary_publisher: "Looney Labs",
    primary_designer: "Andrew Looney",
    developers: [],
    artists: ["Derek Ring"],
    official_url:
      "http://www.looneylabs.com/games/zombie-fluxx?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "taco-cat-goat-cheese-pizza",
    name: "Taco Cat Goat Cheese Pizza",
    id: "0VoFC62ZzA",
    min_players: 3,
    max_players: 8,
    min_playtime: 10,
    max_playtime: 30,
    min_age: 8,
    description:
      "This addictive game is as unique as its name.  It's a power packed quick and simple party game.  Race against each other to SLAP a match between a card and spoken word. But - watch out! - your mind will play tricks on you.  This game was engineered for maximum fun.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1598707861099",
    year_published: 2018,
    primary_publisher: "Dolphin Hat Games",
    primary_designer: "Dave Campbell",
    developers: [],
    artists: [],
    official_url:
      "https://www.dolphinhat.com/taco-cat-goat-cheese-pizza.html?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "exploding-kittens-card-game",
    name: "Exploding Kittens",
    id: "74f9mzbw9Y",
    min_players: 2,
    max_players: 5,
    min_playtime: 10,
    max_playtime: 20,
    min_age: 7,
    description:
      "Exploding Kittens is a card game for people who are into kittens and explosions and laser beams and sometimes goats. In this highly-strategic, kitty-powered version of Russian roulette, players draw cards until someone draws an exploding kitten, at which point they explode, they are Dead, and they are out of the game -- unless that player has a defuse card, which can defuse the kitten using things like laser pointers, belly rubs, and catnip sandwiches. All of the other cards in the deck are used to move, mitigate, or avoid the exploding kittens.",
    image_url:
      "https://s3-us-west-1.amazonaws.com/5cc.images/games/uploaded/1559257206847-51osODpsNIL.jpg",
    year_published: 2015,
    primary_publisher: "Ad Magic, Inc.",
    primary_designer: "Elan Lee",
    developers: [],
    artists: ["Matthew Inman", "Elan Lee", "Shane Small"],
    official_url:
      "https://explodingkittens.com/?utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
  {
    handle: "koi-garden",
    name: "Koi Garden",
    id: "yjghZXawv7",
    min_players: 2,
    max_players: 4,
    min_playtime: 20,
    max_playtime: 30,
    min_age: 7,
    description:
      "Koi Garden is a compact 2-4 player card game about laying pathways for different wildlife to score. Koi Garden features beautiful art, a relaxing theme, and elegant gameplay all packaged together for decades of family fun time.",
    image_url:
      "https://ksr-ugc.imgix.net/assets/033/467/053/ef7f3668f9d1fded178335ef6566ede4_original.jpeg?ixlib=rb-4.0.2&w=700&fit=max&v=1620703616&auto=format&frame=1&q=92&s=d7ffc4a51b43eb8264cc851d34e18549",
    year_published: 2021,
    primary_publisher: "",
    primary_designer: "Floyd Lu",
    developers: [],
    artists: ["Darina Lapkovskaya"],
    official_url:
      "https://www.kickstarter.com/projects/bnbgames/koi-garden-harmonious-gardening-card-game?ref=discovery_category_newest&utm_source=boardgameatlas.com&utm_medium=search&utm_campaign=bga_ads",
  },
];
